# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: mmalone@composableanalytics.com
author_name: Composable
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: theme
labextension_name: jupyterlab-ca-theme
mimetype: ''
mimetype_name: ''
project_short_description: A Jupyter Lab theme for Composable Analytics.
python_name: jupyterlab_ca_theme
repository: https://github.com/Matthew7758/jupyterlabs_composable_theme
test: true
viewer_name: ''

