# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: mmalone@composableanalytics.com
author_name: Composable Analytics
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: theme
labextension_name: jupyterlab-composable-theme
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab theme extension for Composable Analytics.
python_name: jupyterlab_composable_theme
repository: https://github.com/Matthew7758/jupyterlab_composable_theme
test: false
viewer_name: ''

